export const users = [
  {
    id: 1,
    name: 'John',
    age: 28,
    gender: 'Male',
    location: 'New York',
    image: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    bio: 'I love exploring the city and trying new restaurants.',
  },
  {
    id: 2,
    name: 'Alice',
    age: 25,
    gender: 'Female',
    location: 'Los Angeles',
    image: 'https://t4.ftcdn.net/jpg/03/83/25/83/240_F_383258331_D8imaEMl8Q3lf7EKU2Pi78Cn0R7KkW9o.jpg',
    bio: 'Passionate about photography and hiking on weekends.',
  },
  {
    id: 3,
    name: 'Michael',
    age: 32,
    gender: 'Male',
    location: 'Chicago',
    image: 'https://images.pexels.com/photos/2688007/pexels-photo-2688007.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    bio: 'Tech enthusiast and avid gamer.',
  },
  {
    id: 4,
    name: 'Sophia',
    age: 22,
    gender: 'Female',
    location: 'San Francisco',
    image: 'https://images.pexels.com/photos/2052858/pexels-photo-2052858.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    bio: 'Art lover and aspiring painter.',
  },
  {
    id: 5,
    name: 'Daniel',
    age: 29,
    gender: 'Male',
    location: 'Miami',
    image: 'https://example.com/daniel.jpg',
    bio: 'Software engineer by day, aspiring chef by night.',
  },
  {
    id: 6,
    name: 'Emma',
    age: 27,
    gender: 'Female',
    location: 'Seattle',
    image: 'https://images.pexels.com/photos/1239288/pexels-photo-1239288.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    bio: 'Bookworm, coffee enthusiast, and aspiring world traveler.',
  },
  {
    id: 7,
    name: 'Matthew',
    age: 31,
    gender: 'Male',
    location: 'Boston',
    image: 'https://images.pexels.com/photos/2688007/pexels-photo-2688007.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    bio: 'Fitness freak and outdoor sports enthusiast.',
  },
  {
    id: 8,
    name: 'Olivia',
    age: 26,
    gender: 'Female',
    location: 'Austin',
    image: 'https://images.pexels.com/photos/3419676/pexels-photo-3419676.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    bio: 'Passionate about environmental causes and sustainable living.',
  },
  {
    id: 9,
    name: 'Christopher',
    age: 30,
    gender: 'Male',
    location: 'Denver',
    image: 'https://images.pexels.com/photos/3989006/pexels-photo-3989006.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    bio: 'Musician and coffee connoisseur.',
  },
  {
    id: 10,
    name: 'Ava',
    age: 24,
    gender: 'Female',
    location: 'Portland',
    image: 'https://t4.ftcdn.net/jpg/03/83/25/83/240_F_383258331_D8imaEMl8Q3lf7EKU2Pi78Cn0R7KkW9o.jpg',
    bio: 'Nature lover and adventure seeker.',
  },
  {
    id: 11,
    name: 'Ryan',
    age: 33,
    gender: 'Male',
    location: 'San Diego',
    image: 'https://images.pexels.com/photos/1752126/pexels-photo-1752126.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    bio: 'Travel enthusiast and aspiring travel blogger.',
  },
  {
    id: 12,
    name: 'Ella',
    age: 23,
    gender: 'Female',
    location: 'Houston',
    image: 'https://images.pexels.com/photos/3310695/pexels-photo-3310695.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    bio: 'Yoga enthusiast and wellness advocate.',
  },
  {
    id: 13,
    name: 'Andrew',
    age: 28,
    gender: 'Male',
    location: 'Philadelphia',
    image: 'https://images.pexels.com/photos/1752126/pexels-photo-1752126.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    bio: 'Passionate about technology and always up for a good hackathon.',
  },
  {
    id: 14,
    name: 'Grace',
    age: 29,
    gender: 'Female',
    location: 'Detroit',
    image: 'https://images.pexels.com/photos/3419676/pexels-photo-3419676.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    bio: 'Fitness enthusiast and advocate for a healthy lifestyle.',
  },
  {
    id: 15,
    name: 'Tyler',
    age: 30,
    gender: 'Male',
    location: 'Phoenix',
    image: 'https://images.pexels.com/photos/2688007/pexels-photo-2688007.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    bio: 'Gamer and technology geek.',
  },
  {
    id: 16,
    name: 'Chloe',
    age: 25,
    gender: 'Female',
    location: 'Atlanta',
    image: 'https://images.pexels.com/photos/1239288/pexels-photo-1239288.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    bio: 'Fashionista and aspiring model.',
  },
  {
    id: 17,
    name: 'Brandon',
    age: 27,
    gender: 'Male',
    location: 'Nashville',
    image: 'https://images.pexels.com/photos/3419676/pexels-photo-3419676.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    bio: 'Coffee addict and coding enthusiast.',
  },
  {
    id: 18,
    name: 'Zoe',
    age: 26,
    gender: 'Female',
    location: 'Las Vegas',
    image: 'https://images.pexels.com/photos/1239288/pexels-photo-1239288.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    bio: 'Coffee addict and coding enthusiast.', // Same bio as Brandon
  },
  {
    id: 19,
    name: 'Justin',
    age: 32,
    gender: 'Male',
    location: 'Orlando',
    image: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    bio: 'Outdoor enthusiast and adventure seeker.',
  },
  {
    id: 20,
    name: 'Mia',
    age: 24,
    gender: 'Female',
    location: 'New Orleans',
    image: 'https://images.pexels.com/photos/2052858/pexels-photo-2052858.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    bio: 'Animal lover and aspiring veterinarian.',
  },
];
